<?php
    $title    = $templateValues['title'];
    $entity   = $templateValues['entity'];
    $rows     = $templateValues['rows'];
    $titleRow = $templateValues['titleRow'];
?>
<!DOCTYPE html>
<html>
<head>
    <title>CRUD | <?=$title;?></title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
<div class="table-responsive">
    <table class="table">
        <caption><?=$title;?></caption>
        <thead>
            <tr>
            <?php
                foreach ($titleRow as $titleCell):
                    if (!$titleCell->isHideOnList()):
            ?>
                <th scope="col"><?=$titleCell->getCaption();?></th>
            <?php
                    endif;
                endforeach;
            ?>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($rows as $row): ?>
            <tr>
                <?php
                    foreach ($row as $cell):
                        if (!$cell->isHideOnList()):
                ?>
                    <td><?=$cell->getValue();?></td>
                <?php
                        endif;
                    endforeach;
                ?>
                    <td>--//--</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <thead>
            <tr>
            <?php
                foreach ($titleRow as $titleCell):
                    if (!$titleCell->isHideOnList()):
            ?>
                <th scope="col"><?=$titleCell->getCaption();?></th>
            <?php
                    endif;
                endforeach;
            ?>
            <th scope="col">Actions</th>
            </tr>
        </thead>
    </table>
</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addForm">
  Add
</button>










<?php if(!empty($entity->getListAction())): ?>


<!-- Modal -->
<div class="modal fade" id="addForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add1</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">



<form>
  <?php foreach ($entity->getFields() as $field): ?>
  <div class="form-group">
    <label for="addForm<?=$field->getName();?>"><?=$field->getCaption();?></label>
    <input type="text" class="form-control" id="addForm<?=$field->getName();?>" placeholder="<?=$field->getCaption();?>" name="<?=$field->getName();?>">
  </div>
  <?php endforeach; ?>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<?php endif; ?>




</body>
</html>